2021-06-01 11:45:36,213: DEBUG [baseDatos_alarma.py:142] Inicio de with método __enter__
2021-06-01 11:45:36,214: ERROR [baseDatos_alarma.py:48] Error al conectar a la BD: unable to open database file
2021-06-01 11:47:25,347: DEBUG [baseDatos_alarma.py:142] Inicio de with método __enter__
2021-06-01 11:47:25,350: DEBUG [baseDatos_alarma.py:44] Conexión exitosa: <sqlite3.Connection object at 0x0000029DD73134E0>
2021-06-01 11:47:25,350: DEBUG [baseDatos_alarma.py:68] Se abrio el cursor con éxito: <sqlite3.Cursor object at 0x0000029DD734B650>
2021-06-01 11:47:25,352: DEBUG [baseDatos_alarma.py:162] Se ejecuta método __exit__()
2021-06-01 11:47:25,380: DEBUG [baseDatos_alarma.py:172] Commit de la transacción
2021-06-01 11:47:25,381: DEBUG [baseDatos_alarma.py:98] Se han cerrado los objetos de conexión y cursor
2021-06-01 11:47:25,391: DEBUG [baseDatos_alarma.py:142] Inicio de with método __enter__
2021-06-01 11:47:25,392: DEBUG [baseDatos_alarma.py:44] Conexión exitosa: <sqlite3.Connection object at 0x0000029DD73134E0>
2021-06-01 11:47:25,393: DEBUG [baseDatos_alarma.py:68] Se abrio el cursor con éxito: <sqlite3.Cursor object at 0x0000029DD734B6C0>
2021-06-01 11:47:25,394: DEBUG [baseDatos_alarma.py:162] Se ejecuta método __exit__()
2021-06-01 11:47:25,395: DEBUG [baseDatos_alarma.py:172] Commit de la transacción
2021-06-01 11:47:25,396: DEBUG [baseDatos_alarma.py:98] Se han cerrado los objetos de conexión y cursor
2021-06-01 11:47:25,423: DEBUG [SeccionDeberes.py:98] Sistema de deberes cargado
2021-06-01 11:47:25,425: DEBUG [SeccionDeberes.py:501] Cargando deberes guardados
2021-06-01 11:47:25,425: DEBUG [SeccionDeberes.py:505] Abriendo al archivo: GUI\CUERPO/RECURSOS/DATOS/deberes.txt para cargar los datos de los deberes guardados la ultima vez
2021-06-01 11:47:25,427: DEBUG [SeccionDeberes.py:518] Lista de los datos de los deberes cargada: ['0,12']
2021-06-01 11:47:27,787: DEBUG [baseDatos_alarma.py:142] Inicio de with método __enter__
2021-06-01 11:47:27,790: DEBUG [baseDatos_alarma.py:44] Conexión exitosa: <sqlite3.Connection object at 0x0000029DD73134E0>
2021-06-01 11:47:27,791: DEBUG [baseDatos_alarma.py:68] Se abrio el cursor con éxito: <sqlite3.Cursor object at 0x0000029DD734B7A0>
2021-06-01 11:47:27,792: DEBUG [baseDatos_alarma.py:162] Se ejecuta método __exit__()
2021-06-01 11:47:27,793: DEBUG [baseDatos_alarma.py:172] Commit de la transacción
2021-06-01 11:47:27,794: DEBUG [baseDatos_alarma.py:98] Se han cerrado los objetos de conexión y cursor
2021-06-01 11:47:27,795: DEBUG [baseDatos_alarma.py:142] Inicio de with método __enter__
2021-06-01 11:47:27,796: DEBUG [baseDatos_alarma.py:44] Conexión exitosa: <sqlite3.Connection object at 0x0000029DD73134E0>
2021-06-01 11:47:27,797: DEBUG [baseDatos_alarma.py:68] Se abrio el cursor con éxito: <sqlite3.Cursor object at 0x0000029DD734B7A0>
2021-06-01 11:47:27,798: DEBUG [baseDatos_alarma.py:162] Se ejecuta método __exit__()
2021-06-01 11:47:27,799: DEBUG [baseDatos_alarma.py:172] Commit de la transacción
2021-06-01 11:47:27,800: DEBUG [baseDatos_alarma.py:98] Se han cerrado los objetos de conexión y cursor
2021-06-01 11:47:33,366: DEBUG [SeccionDeberes.py:579] Iniciando el proceso de  respaldar los datos de los deberes
2021-06-01 11:47:33,367: DEBUG [SeccionDeberes.py:591] Lista de datos a respaldar generada: ['0,12']
2021-06-01 11:47:33,368: DEBUG [SeccionDeberes.py:592] Abriendo archivo: GUI\CUERPO/RECURSOS/DATOS/deberes.txt para guardar los datos de la lista
2021-06-01 11:47:33,369: DEBUG [SeccionDeberes.py:595] Datos guardados con exito en el archivo
2021-06-01 11:47:33,372: DEBUG [baseDatos_alarma.py:142] Inicio de with método __enter__
2021-06-01 11:47:33,373: DEBUG [baseDatos_alarma.py:44] Conexión exitosa: <sqlite3.Connection object at 0x0000029DD73134E0>
2021-06-01 11:47:33,374: DEBUG [baseDatos_alarma.py:68] Se abrio el cursor con éxito: <sqlite3.Cursor object at 0x0000029DD734B570>
2021-06-01 11:47:33,378: DEBUG [baseDatos_alarma.py:162] Se ejecuta método __exit__()
2021-06-01 11:47:33,379: DEBUG [baseDatos_alarma.py:172] Commit de la transacción
2021-06-01 11:47:33,380: DEBUG [baseDatos_alarma.py:98] Se han cerrado los objetos de conexión y cursor
2021-06-01 11:48:46,206: DEBUG [baseDatos_alarma.py:142] Inicio de with método __enter__
2021-06-01 11:48:46,207: DEBUG [baseDatos_alarma.py:44] Conexión exitosa: <sqlite3.Connection object at 0x000001B6E90D34E0>
2021-06-01 11:48:46,208: DEBUG [baseDatos_alarma.py:68] Se abrio el cursor con éxito: <sqlite3.Cursor object at 0x000001B6E910B650>
2021-06-01 11:48:46,211: DEBUG [baseDatos_alarma.py:162] Se ejecuta método __exit__()
2021-06-01 11:48:46,212: DEBUG [baseDatos_alarma.py:172] Commit de la transacción
2021-06-01 11:48:46,212: DEBUG [baseDatos_alarma.py:98] Se han cerrado los objetos de conexión y cursor
2021-06-01 11:48:46,220: DEBUG [baseDatos_alarma.py:142] Inicio de with método __enter__
2021-06-01 11:48:46,221: DEBUG [baseDatos_alarma.py:44] Conexión exitosa: <sqlite3.Connection object at 0x000001B6E90D34E0>
2021-06-01 11:48:46,222: DEBUG [baseDatos_alarma.py:68] Se abrio el cursor con éxito: <sqlite3.Cursor object at 0x000001B6E910B6C0>
2021-06-01 11:48:46,223: DEBUG [baseDatos_alarma.py:162] Se ejecuta método __exit__()
2021-06-01 11:48:46,224: DEBUG [baseDatos_alarma.py:172] Commit de la transacción
2021-06-01 11:48:46,225: DEBUG [baseDatos_alarma.py:98] Se han cerrado los objetos de conexión y cursor
2021-06-01 11:48:46,251: DEBUG [SeccionDeberes.py:98] Sistema de deberes cargado
2021-06-01 11:48:46,252: DEBUG [SeccionDeberes.py:501] Cargando deberes guardados
2021-06-01 11:48:46,253: DEBUG [SeccionDeberes.py:505] Abriendo al archivo: GUI\CUERPO/RECURSOS/DATOS/deberes.txt para cargar los datos de los deberes guardados la ultima vez
2021-06-01 11:48:46,254: DEBUG [SeccionDeberes.py:518] Lista de los datos de los deberes cargada: ['0,12']
2021-06-01 11:48:49,005: DEBUG [SeccionDeberes.py:579] Iniciando el proceso de  respaldar los datos de los deberes
2021-06-01 11:48:49,008: DEBUG [SeccionDeberes.py:591] Lista de datos a respaldar generada: ['0,12']
2021-06-01 11:48:49,010: DEBUG [SeccionDeberes.py:592] Abriendo archivo: GUI\CUERPO/RECURSOS/DATOS/deberes.txt para guardar los datos de la lista
2021-06-01 11:48:49,017: DEBUG [SeccionDeberes.py:595] Datos guardados con exito en el archivo
2021-06-01 11:48:49,023: DEBUG [baseDatos_alarma.py:142] Inicio de with método __enter__
2021-06-01 11:48:49,025: DEBUG [baseDatos_alarma.py:44] Conexión exitosa: <sqlite3.Connection object at 0x000001B6E90D34E0>
2021-06-01 11:48:49,027: DEBUG [baseDatos_alarma.py:68] Se abrio el cursor con éxito: <sqlite3.Cursor object at 0x000001B6E910B5E0>
2021-06-01 11:48:49,031: DEBUG [baseDatos_alarma.py:162] Se ejecuta método __exit__()
2021-06-01 11:48:49,033: DEBUG [baseDatos_alarma.py:172] Commit de la transacción
2021-06-01 11:48:49,034: DEBUG [baseDatos_alarma.py:98] Se han cerrado los objetos de conexión y cursor
